services:
  - type: web
    name: HR-Management-System
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    startCommand: gunicorn --bind 0.0.0.0:${PORT:-8000} --workers 2 --worker-class sync --timeout 120 run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true

